name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
    inputs:
      worker_file:
        description: 'Path to the worker file'
        required: true
      worker_name:
        description: 'Name of the worker'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy ${{ github.event.inputs.worker_file }} --name ${{ github.event.inputs.worker_name }}